### ISSUE TITLE
Add Pester Tests

### ISSUE THREAD

**Issue by Cirzen** [Cirzen/BigAsciiChars#10]
Before publishing to the gallery ( #9 ) I think the module would benefit from being made safer to modify via a set of Pester Tests.

**Comment by Tuxhedoh** [comment]
I haven't implemented Pester tests for any of my scripts, though I have read about them and done some basic tutorials. Do you have an idea how these should be implemented for this module? I'd be happy to work on it if you can provide guidance, though I understand if you need someone more skilled to work on it.

**Comment by Cirzen** [comment]
I would start with the GetLetterRow and GetLetterColumn functions - make sure that for a selection of characters, the output is as expected. I don't think you have to get complicated with them, they can always be expanded later.
The Write-* functions are harder to test, but you might want to add tests to show they don't throw exceptions for known good inputs.

**Comment by omiossec** [comment]
I will send you a PR
It will test the module manifest to be sure it can be accepted by PowerShell 
and tests for 
* GetCharWidth
* GetLetterColumn
* Write-BigText

Also a CI should be great, you can use Azure DevOps or GitHub Action

**Comment by Cirzen** [comment]
Very cool, thanks @omiossec , et à Samedi :)
@Tuxhedoh GetLetterRow still needs some tests. If you wanted, you could follow the style Oliver has done and add those? Feel free to shout if you need additional help.

**Comment by Cirzen** [comment]
#18 Added a sufficient number for now
