### ISSUE TITLE
Support multiple font styles

### ISSUE THREAD

**Issue by Windos** [Cirzen/BigAsciiChars#3]
Specifically, I'm thinking of the font used for sprites on a [CodeBug](http://www.codebug.org.uk):

![codebugfont](https://user-images.githubusercontent.com/6955786/46846025-76b81280-ce3a-11e8-8697-b95e75111d50.PNG)

I'm sure there are numerous styles that could end up being leveraged... it'd just be multiple `$Codes` hashtables.

**Comment by Cirzen** [comment]
Yes, I definitely agree. I also wanted to put in a 7x9 font as well, mirroring the font used by National Rail at train stations. I think that one looks particularly nice.

**Comment by Cirzen** [comment]
Have been thinking more about this, I think the introduction of a class, `AsciiFont` or similar could achieve this nicely, also containing metadata about the overall size, to allow the display size to adjust accordingly.

**Comment by Cirzen** [comment]
I've started work on this in a new branch: feature/FontClass
